version: '2'

volumes:
  es-data:
  es-logs:

services:
  elasticsearch:
    container_name: elasticsearch
    restart: always
    build: ./elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms5g -Xmx5g"
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - es-logs:/usr/share/elasticsearch/logs
    network_mode: bridge

  kibana:
    container_name: kibana
    restart: always
    build: ./kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    network_mode: bridge

#  logstash:
#    container_name: logstash
#    restart: always
#    image: docker-registry.adfinance.cz/service/elk/logstash:latest
#    ports:
#      - 5000:5000
#      - "5044:5044"
#      - "18910:18910/udp"
#    environment:
#      LS_JAVA_OPTS: "-Xms5g -Xmx5g"
#    links:
#      - elasticsearch
#    networks:
#      - feesy
#      - feesy-elk
