## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana/blob/master/config/kibana.yml

server.name: kibana
server.host: "0"

elasticsearch.url: http://elasticsearch:9200
elasticsearch.username: elastic
elasticsearch.password: ud4xlGayJxeSHMFV1Amn

xpack.monitoring.ui.container.elasticsearch.enabled: true
xpack.monitoring.enabled: true
xpack.security.enabled: true
